### ISSUE TITLE
Confusing Hikey boot recovery documentation

### ISSUE THREAD

**Issue by ubitux** [96boards/documentation#359]
The documentation at https://github.com/96boards/documentation/blob/master/consumer/hikey/installation/board-recovery.md looks broken in several ways:

1. The sentence "The following fastboot commands" is not followed immediately by commands

2. The command `sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin` is actually indicated to be run twice; do we actually need to do that two times in row?

3. For some reason, something doesn't look right or is incomplete because `fastboot` commands don't actually do anything here:
```
% sudo fastboot devices
% sudo fastboot flash ptable ptable-linux-8g.img
< waiting for any device >
```

4. The distributed `hisi-idt.py` script is python2 only, this should be either fixed or documented

5. The USB product reference looks kind of broken, is this on purpose?
```[256899.109073] usb 1-3: new full-speed USB device number 19 using xhci_hcd
[256899.236339] usb 1-3: New USB device found, idVendor=12d1, idProduct=3609
[256899.236344] usb 1-3: New USB device strings: Mfr=1, Product=4, SerialNumber=0
[256899.236347] usb 1-3: Product: \xe3\x84\xb0㌲㔴㜶㤸
[256899.236350] usb 1-3: Manufacturer: 䕇䕎䥎
[256960.693553] usb 1-3: USB disconnect, device number 19
```

Edit: on serial port, this is what I see when following the procedure:
```
% miniterm.py --raw --eol=lf /dev/ttyUSB0 115200
--- Miniterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
usb reset intr
reset device done.
start enum.
enum done intr
Enum is starting.
usb reset intr
enum done intr
NULL package
NULL package
USB ENUM OK.
init ser device done....
usb ata recieving 60s time out....
Switch to UART download...
```

**Comment by Mani-Sadhasivam** [comment]
Hi @ubitux,

Thanks a lot for the detailed findings!

> The sentence "The following fastboot commands" is not followed immediately by commands

I will fix this section

> The command sudo python hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin is actually indicated to be run twice; do we actually need to do that two times in row?

No it is not needed. Will fix this.

> % sudo fastboot devices
> % sudo fastboot flash ptable ptable-linux-8g.img
> < waiting for any device >

This is not an issue with the documentation and it generally means your board didn't get into fastboot mode. Please try flashing the correct images. But the image location itself needs to be fixed, so please follow the process once I have updated the documentation.

> The distributed hisi-idt.py script is python2 only, this should be either fixed or documented

This needs to be documented.

> The USB product reference looks kind of broken, is this on purpose?

This is done on purpose I guess. You can expect these vendor strings for HiSilicon's proprietary interfaces.

Thanks once again for quoting as much as information required to fix the issue. Much appreciated!

@sdrobertw Can we make this as an example for "Good First Issue"? :)

**Comment by ubitux** [comment]
> This is not an issue with the documentation and it generally means your board didn't get into fastboot mode. Please try flashing the correct images. But the image location itself needs to be fixed

I tried both release (https://snapshots.linaro.org/96boards/reference-platform/components/uefi-staging/latest/hikey/release/l-loader.bin) and debug (https://snapshots.linaro.org/96boards/reference-platform/components/uefi-staging/latest/hikey/release/l-loader.bin).

Are you saying these are incorrect loaders?

**Comment by ubitux** [comment]
Same issue, fastboot device not detected.

BTW, if I pick `hisi-idt.py` from the base URL you propose (http://releases.linaro.org/96boards/hikey/linaro/binaries/latest), it doesn't work at all:

```+----------------------+
 Serial:  /dev/ttyUSB0
 Image1:  l-loader.bin
 Image2:  
+----------------------+

Sending l-loader.bin ...
Traceback (most recent call last):
  File "hisi-idt.py", line 262, in <module>
    main(sys.argv[1:])
  File "hisi-idt.py", line 259, in main
    burnboot('hi3716cv200', dev, img1, img2)
  File "hisi-idt.py", line 201, in burnboot
    downloader.download(filename1, filename2)
  File "hisi-idt.py", line 186, in download
    self.senddata(data,self.bootheadaddress[self.chip])
  File "hisi-idt.py", line 169, in senddata
    self.sendheadframe(length,address)
  File "hisi-idt.py", line 124, in sendheadframe
    self.s.setTimeout(0.03)
AttributeError: 'Serial' object has no attribute 'setTimeout'
```

It's probably too old.

On the other hand, the `hisi-idt.py` from https://snapshots.linaro.org/96boards/reference-platform/components/uefi-staging/latest/hikey/ (current documentation) works but is kind of broken since https://github.com/96boards/burn-boot/commit/cf2768645ae72ce0c99c8c9934fc483155fd0fb3

Basically, this commit is supposed to add support for python3, but:

1. it breaks python2 output:

```
+----------------------+
(' Serial: ', '/dev/ttyUSB0')
(' Image1: ', 'l-loader.bin')
(' Image2: ', '')
+----------------------+

('Sending', 'l-loader.bin', '...')
```

Instead of:

```
+----------------------+
 Serial:  /dev/ttyUSB0
 Image1:  l-loader.bin
 Image2:  
+----------------------+

Sending l-loader.bin ...
```

But more importantly, it simply doesn't work in python3:

```
sudo python3 hisi-idt.py -d /dev/ttyUSB0 --img1=l-loader.bin
+----------------------+
 Serial:  /dev/ttyUSB0
 Image1:  l-loader.bin
 Image2:  
+----------------------+

Sending l-loader.bin ...
Traceback (most recent call last):
  File "hisi-idt.py", line 272, in <module>
    main(sys.argv[1:])
  File "hisi-idt.py", line 269, in main
    burnboot('hi3716cv200', dev, img1, img2)
  File "hisi-idt.py", line 201, in burnboot
    downloader.download(filename1, filename2)
  File "hisi-idt.py", line 186, in download
    self.senddata(data,self.bootheadaddress[self.chip])
  File "hisi-idt.py", line 169, in senddata
    self.sendheadframe(length,address)
  File "hisi-idt.py", line 135, in sendheadframe
    crc = self.calc_crc(data)
  File "hisi-idt.py", line 91, in calc_crc
    crc = ((crc << 8) | ord(char)) ^ self.crctable[(crc >> 8) & 0xff]
TypeError: ord() expected string of length 1, but int found
make: *** [Makefile:19: flash] Error 1
```

I know this is not really related to the documentation itself, but it looks like there is quite a mess with regard to these files.

**Comment by Mani-Sadhasivam** [comment]
Submitted a fix #365 

Btw, `hisi-idt.py` script only works with Python2.7. I have added this limitation to the doc.

**Comment by ubitux** [comment]
> Submitted a fix #365

Alright, I get it working following your instructions in your branch, thanks a lot.

Just a few more comments:

- The *see the "Problems with Python Downloader" section below* refers to something that doesn't exist (anymore?)
- You should probably say a green LED turns on when it's supposed to work
- Suggestion: you should pack all the downloads (that is, including `hisi-idt.py`) in the same place, to prevent a delay for the user while following the instructions (which would cause him to start the install process from the beginning)
- Minor typo: missing space before parenthesis in "browser(above links)" and "prompt(below commands)"
- It might be obvious but I'd add a note about disconnecting any serial interface other than USB, because they seem to conflict with each other, and are source of failures in various situation

In any case, thanks a lot, at least I'm able to get it working now. 

> Btw, hisi-idt.py script only works with Python2.7. I have added this limitation to the doc.

Yes but it badly supports python2, stdout is broken (see previous comment). Also, it is actually supposed to support python3 given the commit I linked.
